name: spos
description: SPOS adalah Store POS (Point of Sales)

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # a http rest client
  dio: ^4.0.0

  # toast message or flushbar for notification
  fluttertoast: ^8.0.8

  # load svg
  flutter_svg: ^0.22.0

  # injection
  get_it: ^7.2.0

  # translations
  intl: ^0.17.0

  # materrial dialog
  material_dialog: ^1.0.0-nullsafety.1

  # manage state apps
  # use the power of observable, actions, and reactions to supercharged
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2

  # helper easily exposes a value using inheritedWidget
  sembast: ^3.1.1
  path_provider: ^2.0.5
  provider: ^6.0.0

  # list all dependencies firebase
  # firebase core
  firebase_core: ^1.6.0
  # firebase remote config for any value
  firebase_remote_config: ^0.11.0
  # firebase cloud messaging
  firebase_messaging: ^10.0.7
  flutter_local_notifications: ^8.2.0
  # firebase dynamic links
  firebase_dynamic_links: ^2.0.10

  # shared preferences
  shared_preferences: ^2.0.8

  # validator string
  validators: ^3.0.0

  # json annotation
  json_annotation: ^4.1.0

  # google fonts
  google_fonts: ^2.1.0

  # package info
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  # generator splash screen and icon launcher
  flutter_native_splash: ^1.2.4
  flutter_launcher_icons: ^0.9.2

  analyzer: ^2.3.0
  build_runner: ^2.1.2
  mobx_codegen: ^2.0.3
  # json serializable
  json_serializable: ^5.0.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# for generate splash_screen automatically
flutter_native_splash:
  color: "#1956B4"
  image: assets/images/main_splashscreen.png
  android_gravity: center
  ios_content_mode: center

# for generate icon launcher application
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icons/main_ic_launcher.png
